---
- name: Disk Cleanup Rulebook
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 8080
        endpoint: /webhook
  rules:
    - name: Low Disk Space
      condition: event.disk_space < 20
      action:
        run_playbook:
          name: disk_cleanup_playbook.yml

