---
- name: Zabbix Test rulebook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: print output
      condition: event.payload is defined
      action:
        debug:
          msg:
            - EVENT WAS NOT PROCESSED
            - "EVENT IS {{ event.payload.info }}"


