---
- name: Debug Rulebook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: print output
      condition: event.payload is defined
      actions:
        - debug:
            msg:
              - EVENT WAS PROCESSED
              - "EVENT IS {{ event }}"
        - debug:
            msg: "EVENT PAYLOAD IS {{ event.payload }}"
        - run:
            name: Send Notification
            action:
              module: some_notification_module
              args:
                event_source: "{{ event.payload.source }}"  # 确保这里的source字段正确
