---
- name: Disk Cleanup Rulebook
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 10.11.20.3
        port: 8080
        endpoint: /webhook
  rules:
    - name: Low Disk Space
      condition: event.disk_space < 20
      action:
        run_playbook:
          name: disk_cleanup_rulebook.yml

