---
- name: Disk Cleanup Rulebook
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 10.11.21.93
        port: 5001
  rules:
    #    - name: Low Disk Space
    #      condition: event.disk_space < 20
    #      action:
    #        run_playbook:
    #          name: disk_cleanup_rulebook.yml
    - name: print output
      condition: event.payload is defined
      action:
        debug:
          msg:
            - EVENT WAS NOT PROCESSED
            - "EVENT IS {{ event }}"



